services:

  mars-simulator:
    image: mars-iot-simulator:multiarch_v1
    container_name: mars-simulator
    ports: 
      - "8080:8080"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: mars-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: mars
      RABBITMQ_DEFAULT_PASS: mars
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  ingestion-service:
    build:
      context: ./ingestion-service
    container_name: mars-ingestion-service
    ports:
      - "8000:8000"
    environment:
      SIMULATOR_BASE_URL: http://mars-simulator:8080
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: mars
      RABBITMQ_PASS: mars
      RABBITMQ_EXCHANGE: mars.events
      RABBITMQ_QUEUE: sensor.events
      RABBITMQ_REST_SENSORS_ROUTING_KEY: sensor.rest
      POLL_INTERVAL_SECONDS: 5
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mars_rules
      POSTGRES_USER: mars
      POSTGRES_PASSWORD: mars
    volumes:
      - ./ingestion-service:/app
    depends_on:
      - rabbitmq
      - mars-simulator
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: mars-db
    environment:
      POSTGRES_USER: mars
      POSTGRES_PASSWORD: mars
      POSTGRES_DB: mars_rules
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    depends_on:
      - mars-simulator
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mars -d mars"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  rule-service:
    build:
      context: ./rule-service
    container_name: mars-rule-service
    ports:
      - "8001:8001"
    volumes:
      - ./rule-service:/app
    depends_on:
      ingestion-service:
        condition: service_started
      rabbitmq:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: unless-stopped

  dashboard-service:
    build:
      context: ./dashboard-service
    container_name: mars-dashboard-service
    ports:
      - "8003:8003"
    volumes:
      - ./dashboard-service:/app
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: mars
      RABBITMQ_PASS: mars
      RABBITMQ_EXCHANGE: mars.events
      RABBITMQ_QUEUE: sensor.events
      RABBITMQ_REST_SENSORS_ROUTING_KEY: sensor.rest
    depends_on:
      - ingestion-service
    restart: unless-stopped

  actuator-service:
    build:
      context: ./actuator-service
    container_name: mars-actuator-service
    ports:
      - "8004:8004"
    volumes:
      - ./actuator-service:/app
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: mars
      RABBITMQ_PASS: mars
      RABBITMQ_EXCHANGE: mars.events
      RABBITMQ_QUEUE: sensor.events
      RABBITMQ_REST_SENSORS_ROUTING_KEY: sensor.rest
    depends_on:
      - rule-service
    restart: unless-stopped

  frontend-service:
    build:
      context: ./frontend-service
    container_name: mars-frontend-service
    ports:
      - "8002:8002"
    volumes:
      - ./frontend-service:/app
    depends_on:
      - dashboard-service
    restart: unless-stopped

