services:

  mars-simulator:
    image: mars-iot-simulator:multiarch_v1
    container_name: mars-simulator
    ports: 
      - "8080:8080"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: mars-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: mars
      RABBITMQ_DEFAULT_PASS: mars
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  ingestion-service:
    build:
      context: ./ingestion-service
    container_name: mars-ingestion-service
    ports:
      - "8000:8000"
    environment:
      SIMULATOR_BASE_URL: http://mars-simulator:8080
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: mars
      RABBITMQ_PASS: mars
      RABBITMQ_EXCHANGE: mars.events
      RABBITMQ_QUEUE: sensor.events
      RABBITMQ_ROUTING_KEY: sensor.rest
      POLL_INTERVAL_SECONDS: 5
    volumes:
      - ./ingestion-service:/app
    depends_on:
      - rabbitmq
      - mars-simulator
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: mars-db
    environment:
      POSTGRES_USER: mars
      POSTGRES_PASSWORD: mars
      POSTGRES_DB: mars
    ports:
      - "5432:5432"
    volumes:
      - ./source/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - mars-simulator
